### ISSUE TITLE
Useage example?

### ISSUE THREAD

**Issue by gnarr** [HamidTanhaei/razzle-plugin-runtime#1]
Hi Hamid.

Could you provide an usage example?

Thanks!

**Comment by iberodev** [comment]
yes please, could you show how do you config variables?
If it runs at runtime, are we saying that if this is conteinerized and you pass some environment variables to `docker run` this would work? or is it env replacement at **build** time?

**Comment by HamidTanhaei** [comment]
It adds your .env or .env.development variables just in the development process.
in the `razzle.config.js` you should add something like this config:
```
'use strict';

module.exports = {
  plugins: [
      ...,
      'runtimeenv'
  ]
};
```

for the build time, it does not work. Razzle covers ENV variables by default in the build time.
you should serve a build version of your app in docker containers.
