### ISSUE TITLE
Error on usage

### ISSUE THREAD

**Issue by kirankalyan5** [HamidTanhaei/razzle-plugin-runtime#2]
Hi, Thanks for the plugin, 

When I use the plugin as mentioned the readme, I get the following error in the browser.
![image](https://user-images.githubusercontent.com/13114538/69813088-cbab1980-11f1-11ea-9ed7-1b0dac014d0d.png)

I would really appreciate a solution, also FYI, I use typescript.

**Comment by HamidTanhaei** [comment]
Hi @kirankalyan5 
it seems this problem is not related to the plugin, since it doesn't manipulate `proccess.version`.

**Comment by kirankalyan5** [comment]
Thanks, for now, I got it solved by `dotenv-webpack` plugin.
